# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/redlock/all/redlock.rbi
#
# redlock-1.2.2

module Redlock
end
class Redlock::LockError < StandardError
  def initialize(resource); end
end
