# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simple_cache_lock/all/simple_cache_lock.rbi
#
# simple_cache_lock-0.1.4

module SimpleCacheLock
  extend GemConfig::Base::ClassMethods
  include GemConfig::Base
end
class SimpleCacheLock::Error < StandardError
end
